apiVersion: v1
kind: Service
metadata:
  name: growvia-frontend
  namespace: production
spec:
  #The ApiGateway will use ClusterIP as well but weâ€™ll use Ingress
  type: ClusterIP
  selector:
    app: growvia-frontend
  ports:
  - name: frontend
    ##we using NGINX so port is 80 on it
    port: 80
    targetPort: frontend #defined in deployment.yaml
    protocol: TCP